---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1484086/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp document.html $DEPLOYPATH
    - /bin/cp -R languages $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
